# Generated by Django 2.1.11 on 2019-11-04 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191104_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='warehouse',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Warehouse'),
            preserve_default=False,
        ),
    ]
