# Generated by Django 2.2.7 on 2019-11-04 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191104_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='warehouse',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Warehouse'),
            preserve_default=False,
        ),
    ]
