# Generated by Django 2.2.7 on 2019-11-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20191106_1249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderedItem',
        ),
    ]
