# Generated by Django 2.2.7 on 2019-11-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_product_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='#', max_length=255),
        ),
    ]
