# Generated by Django 2.2.7 on 2019-11-06 20:18

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='product',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='warehouse', on_delete=django.db.models.deletion.CASCADE, to='app.Product'),
        ),
    ]
