# Generated by Django 2.2.7 on 2019-11-06 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20191106_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.Warehouse'),
        ),
    ]
