# Generated by Django 2.2.7 on 2019-11-07 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20191106_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Warehouse'),
        ),
    ]
