# Generated by Django 2.2.7 on 2019-11-07 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20191107_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='quantity',
            new_name='per_product',
        ),
    ]
