# Generated by Django 2.2.7 on 2019-11-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20191107_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='per_product',
            new_name='unit_quantity',
        ),
    ]
