# Generated by Django 2.2.7 on 2019-11-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_product_available_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='available_quantity',
            new_name='maximum_available',
        ),
    ]
