# Generated by Django 2.2.7 on 2019-11-07 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20191107_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Batch'),
        ),
    ]
