# Generated by Django 2.2.7 on 2019-11-07 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20191107_1218'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('name', 'batch', 'warehouse')},
        ),
    ]
