# Generated by Django 2.2.7 on 2019-11-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20191107_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='manufacture_place',
            field=models.CharField(default='Cape Town, South Africa', max_length=255),
        ),
    ]
