# Generated by Django 2.2.7 on 2019-11-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20191107_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['product', 'part']},
        ),
    ]
