# Generated by Django 2.2.7 on 2019-11-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20191107_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='number',
            field=models.UUIDField(default='<function uuid4 at 0x110d1bf80>', unique=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_code',
            field=models.UUIDField(default='<function uuid4 at 0x110d1bf80>'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='<function uuid4 at 0x110d1bf80>'),
        ),
    ]
