# Generated by Django 2.2.7 on 2019-11-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20191107_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='number',
            field=models.UUIDField(default='37095e58-4390-4344-8fe7-4a6b46290469', unique=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_code',
            field=models.UUIDField(default='f05990ab-6fe6-4169-8498-e4a8283f5b4b'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='7ceff136-4a69-448a-adfd-cd6a45c88785'),
        ),
    ]
