# Generated by Django 2.2.7 on 2019-11-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20191107_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='number',
            field=models.UUIDField(default='f3acd920-e299-471f-b9d0-4784aee84e9c', unique=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_code',
            field=models.UUIDField(default='3fd3e359-ef75-4d39-bbb0-bb1746813959'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='0c7cc327-20b1-472f-baa8-3c0611c12c4a'),
        ),
    ]
