# Generated by Django 2.2.7 on 2019-11-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20191107_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterField(
            model_name='batch',
            name='number',
            field=models.UUIDField(default='30028fee-a224-4072-b48f-cd60874f0a6c', unique=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_code',
            field=models.UUIDField(default='93c436d7-a7b3-4c14-9108-1202ebd004ef'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='537acf4b-171d-42e7-823e-68384594f2d2'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product_code', 'batch')},
        ),
    ]
