# Generated by Django 2.2.7 on 2019-11-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20191107_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={},
        ),
        migrations.AlterField(
            model_name='batch',
            name='number',
            field=models.UUIDField(default='b3ce871c-6161-42a6-a344-2286661979a6', unique=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_code',
            field=models.UUIDField(default='ae575974-55fd-4eb2-ad33-346d9b101189'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='505a9b40-1de2-475a-b70b-07fb2b35fce5'),
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('part_code', 'batch')},
        ),
    ]
