# Generated by Django 2.2.7 on 2019-11-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20191107_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterField(
            model_name='batch',
            name='number',
            field=models.UUIDField(default='98129f5d-fef7-4476-b1ad-3598f21c0ea3', unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(default='094d80ee-3456-4547-b637-92f3d2fc250d'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_code',
            field=models.UUIDField(default='9fbfc082-8f6e-4a1d-9395-3dec14567760'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='23563fb2-c05f-454e-9f3e-bd030c95cc7f'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('order_name', 'order_number', 'client')},
        ),
    ]
