# Generated by Django 2.2.7 on 2019-11-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20191107_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordereditem',
            options={'ordering': ['product__name']},
        ),
        migrations.AlterField(
            model_name='batch',
            name='number',
            field=models.UUIDField(default='6520a170-8d16-40db-b36b-02371de4341a', unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(default='8ecc79f0-3b4f-4c28-8129-5c6766649884'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_code',
            field=models.UUIDField(default='5f344de2-873c-41e2-8477-65548cb9f5b3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='536f93ae-f803-496c-b7c9-08e753d49ab1'),
        ),
    ]
