# Generated by Django 2.2.7 on 2019-11-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20191107_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='number',
            field=models.UUIDField(default='<function uuid4 at 0x7fade08749d8>', unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(default='fa3fabea-69f6-4875-ba69-5637472b6b05'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_code',
            field=models.UUIDField(default='77716b1b-2954-42d3-991e-ae4b9048fa9c'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='563da4a6-746c-431e-80ca-fdf035496123'),
        ),
        migrations.AlterUniqueTogether(
            name='ordereditem',
            unique_together={('product', 'order')},
        ),
    ]
