# Generated by Django 2.2.7 on 2019-11-09 19:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20191109_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='number',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(default='07d7e4a7-5573-4b8d-8c1f-1829192f4cf2'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_code',
            field=models.UUIDField(default='d981f127-f611-446f-8ded-909a87bb7a85'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='0bfff02b-414f-4352-bf22-db5f6dc82e8f'),
        ),
    ]
