# Generated by Django 2.2.7 on 2019-11-09 19:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20191109_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(default='0112479b-8591-442a-bd1e-f743193c4822'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default='cbfb959c-25b5-46f2-a3e4-dee1715d9686'),
        ),
    ]
