# Generated by Django 2.2.7 on 2019-11-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_auto_20191109_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='number',
            field=models.CharField(default='<function uuid4 at 0x7f652e54a9d8>', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='<function uuid4 at 0x7f652e54a9d8>', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_code',
            field=models.CharField(default='<function uuid4 at 0x7f652e54a9d8>', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='<function uuid4 at 0x7f652e54a9d8>', max_length=255, unique=True),
        ),
    ]
