# Generated by Django 2.2.7 on 2019-11-09 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_auto_20191109_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='<function uuid4 at 0x7fa45a9c09d8>', editable=False, max_length=255),
        ),
    ]
