# Generated by Django 2.2.7 on 2019-11-20 22:28

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_auto_20191119_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='available_total',
            new_name='available',
        ),
        migrations.AddField(
            model_name='part',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='<function uuid4 at 0x7f23e876b9d8>', editable=False, max_length=255),
        ),
        migrations.CreateModel(
            name='PartOrdered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('quantity', models.IntegerField(default=0)),
                ('ordered_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.OrderedItem')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Part')),
            ],
            options={
                'unique_together': {('part', 'ordered_item')},
            },
        ),
    ]
